name: publish
on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  publish-drc-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
            
      - name: Build the hello-docker Docker image
        run: |
          docker build . --tag ghcr.io/locnnil/drc:latest
          docker push ghcr.io/locnnil/drc:latest
